### ISSUE TITLE
Domain Name: aiwaffle.com

### ISSUE THREAD

**Issue by lunw1024** [AIwaffle/AIwaffle#6]
- [x] 申请域名
- [x] 备案

现在可以通过 http://www.aiwaffle.com:8080/ 访问课程
需要整成无须端口访问的 @jimmy-zx @wlt233 

![image](https://user-images.githubusercontent.com/57162668/77987792-57be8080-734d-11ea-9790-8d4afc0899d6.png)

**Comment by jimmy-zx** [comment]
Deployment:

 - [x] Nginx reverse proxy (80 -> 8080)
 - [x] HTTPS access (Let's encrypt)

**Comment by lunw1024** [comment]
well done
