### ISSUE TITLE
Change course names according to the naming convention

### ISSUE THREAD

**Issue by lunw1024** [AIwaffle/AIwaffle#9]
1. All words capitalized, including "to", "and", etc.
2. Explicit words instead of symbols ("And" instead of "&", etc.)
3. Shorten extra-long names (Classify handwriting digits using shallow, deep, and CNN -> Classify Handwritten Digits With Neural Networks

_Also, delete corresponding Kaggle notebooks. Maintain the courses only in one place, with one version_

**Comment by AlienKevin** [comment]
two more naming conventions to add:
4. The only special characters allowed are `-` (dash) and `:` (colon)
5. the course [file paths](https://github.com/AIwaffle/AIwaffle/tree/master/Courses) and course url paths should be derived from the displayed names. The rule is to replace all spaces and `:` (colon) with `-` (dash) and make everything lowercase, like so:

Example 1:
displayed name:
```
Classify Handwritten Digits With Neural Networks
```
path and url name:
```
classify-handwritten-digits-with-neural-networks
```

Example 2:
displayed name:
```
Pytorch: Tensor Manipulation
```
path and url name:
```
pytorch-tensor-manipulation
```

**Comment by lunw1024** [comment]
Done. All course names are changed.
